name: libsemigroups_pybind11_dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - black
  - bs4
  - codespell
  - cpplint
  - fmt
  - ipython
  - lxml
  - pip
  - pylint
  - pytest
  - sphinx
  - sphinx-copybutton
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - pip:
      - accepts
