# name: libsemigroups_pybind11_dev

name: test
channels:
  - conda-forge

dependencies:
  - python=3.12
  - black
  - bs4
  - codespell
  - cpplint
  - fmt
  - ipython
  - lxml
  - pip
  - pylint
  - pytest
  - sphinx
  - sphinx-copybutton
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex
  - pip:
      - accepts

variables:
  LD_LIBRARY_PATH: ${CONDA_PREFIX}/lib:/usr/local/lib
  PKG_CONFIG_PATH: ${CONDA_PREFIX}/lib/pkgconfig:${CONDA_PREFIX}/share/pkgconfig:/usr/local/lib/pkgconfig
