[tool.black]
line-length = 80
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.7.0",
    "pkgconfig>=l.5.0",
    "packaging>=20.4",
]

build-backend = "setuptools.build_meta"
